name: Deploy website to SWA

on:
  push:
    paths: ["src/Modkit/Website/**"]
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 22

      - name: Log into Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: |
          cd src/Modkit/Website
          dotnet tool restore
          dotnet restore
          npm ci
          npm run build
          cp ./staticwebapp.config.json ./dist

      - name: Build and deploy site
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          PRE_BUILD_COMMAND: dotnet tool restore
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/src/Modkit/Website/dist"
          output_location: "/src/Modkit/Website"
